# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 17:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[(b'08:00-08:30', b'08:00-08:30'), (b'08:30-09:00', b'08:30-09:00'), (b'09:00-09:30', b'09:00-09:30'), (b'09:30-10:00', b'09:30-10:00'), (b'10:00-10:30', b'10:00-10:30'), (b'10:30-11:00', b'10:30-11:00'), (b'11:00-11:30', b'11:00-11:30'), (b'11:30-12:00', b'11:30-12:00'), (b'12:00-12:30', b'12:00-12:30'), (b'12:30-13:00', b'12:30-13:00'), (b'13:00-13:30', b'13:00-13:30'), (b'13:30-14:00', b'13:30-14:00'), (b'14:00-14:30', b'14:00-14:30'), (b'14:30-15:00', b'14:30-15:00'), (b'15:00-15:30', b'15:00-15:30'), (b'15:30-16:00', b'15:30-16:00'), (b'16:00-16:30', b'16:00-16:30'), (b'16:30-17:00', b'16:30-17:00'), (b'17:00-17:30', b'17:00-17:30'), (b'17:30-18:00', b'17:30-18:00'), (b'18:00-18:30', b'18:00-18:30'), (b'18:30-19:00', b'18:30-19:00')], max_length=15)),
                ('note', models.CharField(max_length=100)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('login', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'schooluser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Room'),
        ),
    ]
